spring:
  profiles:
    active: local

---

url:
  sbs: http://sbsfune.sbs.co.kr
  billboard: http://billboard.co.kr
  melon: https://www.melon.com
uri:
  melon:
    genre: /genre/song_list.htm?gnrCode=GN
jwt:
  secret: zum.pilot@junil#@!
youtube:
  api_key:
    zum: AIzaSyB9-VhCcc2neB2aYgVxJPZLtkb_jmfNo1o
    myself: AIzaSyAivIxmsxd4b1FA_C67gYKph56F4RseQeY
  number_of_return: 1


